Update API database using OpenPedCan-analysis v12 final release data
PediatricOpenTargets/OpenPedCan-api pull request #87
Opened 2023-05-11 16:41 UTC by logstar

Updated API database using OpenPedCan-analysis v12 final release data. The following filtered files in `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/api-data/` were used for building the API database:

- `efo-mondo-map.tsv`
- `ensg-hugo-pmtl-mapping.tsv`
- `gene-counts-rsem-expected_count-collapsed-deseq.rds`

The filtered files were generated by the `filter-mtp-tables` module in the OpenPedCan-analysis.

Resolved #86 

## Type of change

### Changed

- Updated database using `OpenPedCan-analysis` v12 final release data.
- Changed `db/build_db.sh` to download OpenPedCan-analysis `api-data` using `db/build_tools/download_api_data.sh`.
- Changed `db/build_tools/build_db_docker_cmd.sh` to compress intermediate CSV files.

### Added

- Added `db/build_tools/download_api_data.sh` to download OpenPedCan-analysis `api-data`.

## How Has This Been Tested?

Terminal returns for testing DEV host:

```text
$ API_HOST=dev ./tests/run_tests.sh
API base URL: https://openpedcan-api-dev.d3b.io
✔ |  OK F W S | Context
✔ | 885       | tests/r_test_scripts/test_endpoint_http.R [3952.2 s]

══ Results ════════════════════════════════════════════
Duration: 3952.2 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 885 ]
Done running run_tests.sh
```

For more details about testing environment, options, and resources, see `README.md`.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have emojis in my PR and commits 😉

2023-05-16 20:02 UTC, kelseykeith requested changes
Overall, everything looks good!

- Code is pulling from the v11 data
- Results from the API call match data in OpenPedCan-analysis tables.
- Both tables and plots subset samples correctly based on the subgroup asked for.
- TCGA and GTEx data is handled correctly.

---

Had one issue when test building the database. The `lsb_release` program prints linux base and distribution information. Apparently it used to be installed with ubuntu base, but is no longer. It needs to be included for install separately in `db/build_tools/build_db.Dockerfile` in order to successfully build the database (see example below).
```
# hadolint ignore=DL3008
RUN apt-get update -qq \
  && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    gnupg \
    gosu \
    # Install odbc to operate database
    unixodbc \
    unixodbc-dev \
    odbc-postgresql \
    lsb-release \
  && rm -rf /var/lib/apt/lists/* \
  # Install postgres 11 from an actively maintained, as of Sep 2021, APT
  # repository https://wiki.postgresql.org/wiki/Apt .

```

2023-05-17 12:04 UTC, kelseykeith commented
Yes, I'm fine with that. I can either submit a standalone PR for the issue or include it with my CNV database PR once we get there

2023-05-17 12:05 UTC, kelseykeith approved these changes

2023-05-17 13:24 UTC, logstar commented
Thank you. I will also add `lsb-release` installation to the `db/build_tools/build_db.Dockerfile` before working on the next issue.

I will merge this PR soon to update the QA API site.

2023-05-18 16:27 UTC, merged